<Project Sdk="Microsoft.NET.Sdk.Web">

  <ItemGroup>
    <ProjectReference Include="..\TicketingSystem.DAL\TicketingSystem.DAL.csproj" />
    <ProjectReference Include="..\TicketingSystem.DAL.EF\TicketingSystem.DAL.EF.csproj" />
    <ProjectReference Include="..\TicketingSystem.Domain\TicketingSystem.Domain.csproj" />
  </ItemGroup>

  <ItemGroup>
    <PackageReference Include="Swashbuckle.AspNetCore" Version="9.0.6" />
  </ItemGroup>

  <PropertyGroup>
    <TargetFramework>net10.0</TargetFramework>
    <Nullable>enable</Nullable>
    <ImplicitUsings>enable</ImplicitUsings>
  </PropertyGroup>

</Project>